# Generated by Django 4.2 on 2025-07-09 13:22

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("chat", "0005_message_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="message",
            name="citation",
            field=models.TextField(blank=True, null=True),
        ),
    ]
