# Generated by Django 4.2 on 2025-07-15 10:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("chat", "0006_message_citation"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="message",
            name="citation",
        ),
        migrations.AddField(
            model_name="message",
            name="audio",
            field=models.FileField(blank=True, null=True, upload_to="chat_audio/"),
        ),
        migrations.AddField(
            model_name="message",
            name="cite",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="message",
            name="file",
            field=models.FileField(blank=True, null=True, upload_to="chat_files/"),
        ),
        migrations.CreateModel(
            name="Citation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("text", models.TextField()),
                ("uri", models.URLField()),
                (
                    "message",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="citations",
                        to="chat.message",
                    ),
                ),
            ],
        ),
    ]
