# Generated by Django 4.2 on 2025-07-15 10:32

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("chat", "0007_remove_message_citation_message_audio_message_cite_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="message",
            name="cite",
        ),
    ]
