# Generated by Django 4.2 on 2025-07-16 05:50

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("chat", "0009_message_is_workflow_image_file_audio"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="message",
            name="audio",
        ),
        migrations.RemoveField(
            model_name="message",
            name="file",
        ),
        migrations.RemoveField(
            model_name="message",
            name="image",
        ),
    ]
