# Generated by Django 4.2 on 2025-07-03 07:27

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("slab", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="title",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
