# Generated by Django 4.2 on 2025-07-15 10:32

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("slab", "0002_post_title"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="views",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
