# Generated by Django 4.2 on 2025-07-19 06:47

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("user", "0004_userprofile_following"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="job",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
